### ISSUE TITLE
Issues regarding finding the right vocab size for the pretrained model

### ISSUE THREAD

**Issue by kaifoerster** [Hertie-School-Deep-Learning-Fall-2023/problem-set-3-ps_group_a#1]
@chiara-fb I am having some troubles aligning the input and output dictionary sizes to make the pretrained model work. I have tried to change the prepare_data function to remove words from the dictionary, but it is pretty difficult to remove exactly so that one reaches the pretrained model vocab size, which is torch.Size([11948, 256])  for the encoder and torch.Size([22601, 256]) for the decoder.

**Comment by chiara-fb** [comment]
Hi Kai. Thanks for making me aware of that. The issue is due to the fact that in the original `.csv` languages were swapped, hence the pretrained_weights are not compatible with GER -> EN translation, but rather with EN -> GER. As this was a mistake in the original repo, we will not remove any points for this task.

PS: I attached freshly pretrained weights for EN -> GER, in case you want to test these ones. 

[pretrained_encoder3.zip](https://github.com/Hertie-School-Deep-Learning-Fall-2023/problem-set-3-ps_group_a/files/13442427/pretrained_encoder3.zip)
[pretrained_decoder3.zip](https://github.com/Hertie-School-Deep-Learning-Fall-2023/problem-set-3-ps_group_a/files/13442429/pretrained_decoder3.zip)
